apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: bulk-frontend
  namespace: team-bulk
  labels:
    team: team-bulk
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /api/isalive
  readiness:
    path: /api/isready
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 1
  accessPolicy:
    outbound:
      rules:
        - application: bulk-backend

  ingresses: 
    - "https://bulk.dev.intern.nav.no"