apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: bulk-frontend
  namespace: team-bulk
  labels:
    team: team-bulk
spec:
  image: { { image } }
  port: 3000
  liveness:
    initialDelay: 30
    path: /api/isalive
  readiness:
    initialDelay: 30
    path: /api/isready
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 1
  accessPolicy:
    outbound:
      rules:
        - application: bulk-backend
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      errorPath: /error
      #resources:
      #  limits:
      #    cpu: 250m
      #    memory: 256Mi
      #  requests:
      #    cpu: 20m
      #    memory: 32Mi

  ingresses:
    - "https://bulk.dev.intern.nav.no"
